class Autogenerated {
  List<Articles>? articles;

  Autogenerated({this.articles});

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        articles: List<Articles>.from((json['articles'] as List)
            .map((e) => Articles.fromJson(e as Map<String, dynamic>))
            .toList()),
      );
}

class Articles {
  String? title;

  Articles({this.title});

  Articles.fromJson(Map<String, dynamic> json) {
    title = json['title'];
  }
}
