import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:reactive_way/api_key.dart';
import 'model.dart';

class Service{

  Future<List<Articles>> getData(String? countryCode, String? category) async{

    String url = 'https://newsapi.org/v2/top-headlines?country=$countryCode&category=$category&apiKey=$apiKEY';

    final response = await http.get(Uri.parse(url));
    final data  = json.decode(response.body);
    List<Articles>? articles = Autogenerated.fromJson(data).articles;
    return articles!;
  }
}